#.travis.yml

language: node_js
node_js:
- "6"
- "6.1"
- "5.11"
- "0.6"
- "0.8"
- "0.10"
- "iojs"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
 
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
  -  npm install
  
script: npm test

# safelist
branches:
  only:
  - master

addons:
    code_climate:
        repo_token: 2338893580d4dc286e90634954341488e6898ccb3d7f7fdd25f041cf03f28cb5
